### ISSUE TITLE
cropshot is down

### ISSUE THREAD

**Issue by captainbrosset** [juliandescottes/cropshot#1]
Cropshot appears to be down!!!

**Comment by bcharbonnier** [comment]
#FIXITNAU ! :+1:

**Comment by juliandescottes** [comment]
Don' t know what's happening.

The homepage is hosted by hithub gh-pages : http://juliandescottes.github.io/cropshot/ and can still be used

**Comment by juliandescottes** [comment]
And ... it's back ! No idea what happened.
